### ISSUE TITLE
Coefficients File Corrections

### ISSUE THREAD

**Issue by pernak18** [pernak18/g-point-reduction#7]
in bands where we have no minor contributors in one atmosphere region (lower or upper), i have (from @RobertPincus ):

> in your coefficients files you have contributors_upper = 1 but this should be a multiple of the gpt dimension, i.e. 0, 15, 30…
>
> Note that contributors_upper should be equal to minor_absorber_intervals_upper*ngpt
> 
> I can’t stress enough that it’s important to be sure the coefficients files are being properly formulated. Otherwise you’re reading coefficients for minor gases from random memory locations.
> 
> I just fear investing time in results that turn out to be flawed because the files are busted

seems like a pretty big deal

**Comment by RobertPincus** [comment]
@pernak18 I think the issue may be in the stratosphere, rather than being related to the number of minor contributors, but this is something to run to ground. 

I say this because the relationship between the `minor_absorber_intervals`, `ngpt`, and `contributors` is correct in the lower atmosphere but not in the upper atmosphere, at least in the random coefficients file you sent me.

**Comment by pernak18** [comment]
fixed with 59c782edd85950c1c30393039764d74436cc8010
